### ISSUE TITLE
Allow passing pub/sub clients

### ISSUE THREAD

**Issue by austinkelleher** [TopCloud/sc-redis#11]
Currently, `sc-redis` automatically creates pub/sub Redis clients for you. In some scenarios you may want more control over how clients are created as well as which library the clients are created from. Most popular Redis clients implement the same API ([ioredis](https://github.com/luin/ioredis) in my case).

Example Usage:

```js
const SCBroker = require('socketcluster/scbroker')

function createRedisClient () {
  ...
}

class Broker extends SCBroker {
  async run () {
    const pubClient = await createRedisClient()
    const subClient = await createRedisClient()
    scRedis.attach(this, { pubClient, subClient })
  }
}

new Broker()
```

I have a fix for this and will have a PR up in a few minutes.

**Comment by jondubois** [comment]
Published to npm as `v0.2.0` ;)
