### ISSUE TITLE
unable to persist data to redis

### ISSUE THREAD

**Issue by ericraio** [TopCloud/sc-redis#2]
I can't figure out why i can't persist every message that gets published into the redis database. Right now, if i were to update the servers, all previous messages are lost.

**Comment by jondubois** [comment]
Redis is just meant to act as a dumb data transport layer between all your SC instances, your SC instances should be responsible for handling the messages and persisting them to a database as needed.

**Comment by jondubois** [comment]
If you want a more reliable way to pass data between multiple SC instances, you will need to use an AMQP solution like Rabbit MQ or an MQTT solution like Mosquitto or you can use a third-party pub/sub service which offers guaranteed delivery.
