### ISSUE TITLE
How to subscribe to the channel?

### ISSUE THREAD

**Issue by batazor** [TopCloud/sc-redis#5]
How to subscribe to the channel of a workers?

```
module.exports.run = function (worker) {
   console.log('   >> Worker PID:', process.pid);

    var httpServer = worker.httpServer;

    app = function(req, res) {
         res.end('hello');
    };

     httpServer.on('request', app);

     // ???????????????
     //scRedis.on('message', function(channel, message) {
     //  console.log(message, '<< message');
     //});
      //scRedis.subscribe('testredis');

     httpServer.on('request', function() {});
 };
```

**Comment by jondubois** [comment]
@batazor You can subscribe to a channel from inside a worker through the Global object: http://socketcluster.io/#!/docs/api-global

You can access it from `worker.scServer.global`

So to subscribe you can go:

``` js
var myChannel = worker.scServer.global.subscribe('myChannel');
myChannel.watch(function (data) {
  console.log('Message from myChannel channel:', data);
});
```

**Comment by batazor** [comment]
@jondubois That that I get the message for every running of workers is this normal? I thought should get just one running.

**Comment by jondubois** [comment]
That's expected. If u only want to subscribe in a specific worker, u can check '''worker.id''' and only subscribe if its equal 0 for example.

**Comment by batazor** [comment]
Thanks. This option is not very suitable. Probably I will need to use something else.
